# Generated by Django 5.1.3 on 2024-11-26 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_role_student_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='role',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
